### ISSUE TITLE
reconnect if endpoint is temporarily not reachable

### ISSUE THREAD

**Issue by sf666** [chr-fritz/knx-exporter#52]
**Describe the bug**

I gather data from a knx-bridge located at a different location than the knx-exporter is running. In case the router goes down, the connection to the knx-brige is temporarily unavailable. After the router is up again, the knx-exporter doesn't (re-)connect to the knx-bridge.

**To Reproduce**
1. start the knx-exporter
2. collect data
3. shut down the router. The knx-bridge ip/port is not reachable from knx-exporter location
4. log message : `time="2023-06-22T05:52:49Z" level=info msg="can not send read request for 0/3/0: Connection server has terminated"`
5. get up the router. The knx-bridge ip/port is reachable and responds to port/ip requests from knx-exporter's location
6. log message : `time="2023-06-22T05:57:49Z" level=info msg="can not send read request for 0/3/0: Connection server has terminated"`

**Expected behavior**
At step 6. the knx-exporter should have reconnected to the knx-bridge, collecting data

**Comment by chr-fritz** [comment]
Can you check out if your problem was solved with the latest release [v0.2.7](https://github.com/chr-fritz/knx-exporter/releases/tag/v0.2.7) which includes debian packages including systemd service definition?
