### ISSUE TITLE
DPT 1.011 is currently not working

### ISSUE THREAD

**Issue by nomisim** [chr-fritz/knx-exporter#55]
**Describe the bug**
If one configures a group address with DPT 1.011 (DPT_State), it does not show up on the exported metrics.
In my KNX installations this is the default feedback DPT of a basic switching module.
Can anyone confirm? Maybe I am doing something wrong.
A workaround is to use 1.001 instead. 1.003 is also working.

**To Reproduce**
1. Configure a DPT 1.011 to be exported.
2. see if it gets exported

**Expected behavior**
DPT 1.011 should work too.

**Desktop (please complete the following information):**
 - OS: docker container run on raspbian
 - Version: 0.2.6

**Additional context**

**Comment by chr-fritz** [comment]
The support for reading the DPT 1.011 is added in the latest release [v0.2.7](https://github.com/chr-fritz/knx-exporter/releases/tag/v0.2.7).
